# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  tagName: '$(Build.BuildNumber)'
  imageName: '$(dockerid)/azureplpelineweb:$(tagName)'

steps:
  - script: dotnet build -c Release
    displayName: 'Dotnet build'

  - script: docker build -f AzurePipelineWeb/Dockerfile -t $(imageName) .
    displayName: 'Docker build'

  - script: |
      docker login -u $(dockerid) -p $(password)
      docker push $(imageName)
    displayName: 'Push docker image'

  - task: SSH@0
    displayName: 'Run shell inline on remote machine'
    inputs:
      sshEndpoint: 'aliyun_centos'
      runOptions: inline

      inline: |
        # update deployment image
        kubectl set image deployment/azureplpelineweb azureplpelineweb=$(imageName) --record=true

        # remove old tag image
        docker rmi $(docker images | grep azureplpelineweb | awk '{print $3}') >> /dev/null 2>&1
