pool:
  name: Hosted Ubuntu 1604

steps:
- task: DotNetCoreCLI@2
  displayName: 'Generate coverage report'
  inputs:
    command: test
    projects: 'AzurePipeline.Test/AzurePipeline.Test.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
    publishTestResults: false

- script: |
   dotnet tool install dotnet-sonarscanner --tool-path sonar
   
   sonar/dotnet-sonarscanner begin /k:"AzurePipelineWeb" /d:sonar.host.url="http://sonarqube.codepie.fun" /d:sonar.login="ec4e3a300be713cc5260c68cb2de08d6de4e1567" /d:sonar.cs.opencover.reportsPaths=AzurePipeline.Test/coverage.opencover.xml
   
   dotnet build
   
   sonar/dotnet-sonarscanner end /d:sonar.login="ec4e3a300be713cc5260c68cb2de08d6de4e1567"
   
  displayName: 'Run scanner'
